name: Ansible CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  syntax-check:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install ansible -y

      - name: Ansible Version
        run: ansible --version

      - name: Syntax Check
        run: |
          ansible-playbook playbooks/setup-server.yml \
          --syntax-check